# Generated by Django 5.0.4 on 2024-04-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_alter_task_status_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
    ]
