# Generated by Django 5.0.4 on 2024-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0011_alter_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
