# Generated by Django 5.0.4 on 2024-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0014_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
