# Generated by Django 5.0.4 on 2024-04-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0016_approve_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approve_Task',
        ),
    ]
