# Generated by Django 5.0.4 on 2024-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0020_alter_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
