# Generated by Django 5.0.4 on 2024-04-19 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0021_alter_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
