# Generated by Django 5.0.4 on 2024-04-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0024_remove_user_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
