# Generated by Django 5.0.4 on 2024-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0026_task_assigned_to_user_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
