# Generated by Django 5.0.4 on 2024-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0031_remove_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='code_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
