# Generated by Django 5.0.4 on 2024-05-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0032_alter_topic_code_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='rank',
        ),
    ]
