# Generated by Django 5.0.4 on 2024-05-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0033_remove_topic_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_name', 'chapter', 'course')},
        ),
    ]
