# Generated by Django 5.0.4 on 2024-05-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0034_topic_course_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
    ]
