# Generated by Django 5.0.4 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0036_topic_course_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='topic',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('topic_name', 'chapter', 'course', 'rank')},
        ),
    ]
