# Generated by Django 5.0.4 on 2024-05-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0039_option_questionsection_option_section_quizquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsection',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='questionsection',
            name='correct_answer_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionsection',
            name='html_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questionsection',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hierarchy.quizquestion'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='html_content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
