# Generated by Django 5.0.4 on 2024-05-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0040_remove_questionsection_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsection',
            name='html_content',
        ),
    ]
