# Generated by Django 5.0.4 on 2024-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0041_remove_questionsection_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsection',
            name='correct_answer_text',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
