# Generated by Django 5.0.4 on 2024-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0042_alter_questionsection_correct_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsection',
            name='correct_answer_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
