# Generated by Django 5.0.3 on 2024-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0047_questionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='check_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
