# Generated by Django 5.0.3 on 2024-06-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0048_course_check_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
