# Generated by Django 5.0.3 on 2024-06-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0049_course_quiz_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='quiz_boolean',
        ),
    ]
