# Generated by Django 5.0.3 on 2024-06-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0053_savedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='last_accessed_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed', to='hierarchy.usertopicprogress'),
        ),
    ]
