# Generated by Django 5.0.3 on 2024-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0055_usercoursemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='default.jpg', max_length=100),
        ),
    ]
