# Generated by Django 5.0.3 on 2024-06-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0057_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
