# Generated by Django 5.0.3 on 2024-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0059_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
