# Generated by Django 5.0.3 on 2024-06-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0061_questionnaireresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Team Leader', 'Team Leader'), ('Developer', 'Developer')], default='Developer', max_length=20),
        ),
    ]
