# Generated by Django 5.0.3 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0062_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q1_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q5',
            field=models.IntegerField(default=0),
        ),
    ]
