# Generated by Django 5.0.3 on 2024-06-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0063_alter_questionnaireresponse_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q1',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q1_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q3',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q4',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='q5',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
