# Generated by Django 5.0.3 on 2024-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0065_alter_questionnaireresponse_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='algo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='back',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='basic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='front',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='oop',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='provFront',
            field=models.FloatField(default=0.0),
        ),
    ]
