# Generated by Django 5.0.3 on 2024-06-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0069_user_bio_user_phonenumber'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionsection',
            unique_together={('question', 'section_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('course', 'question_number')},
        ),
    ]
